### ISSUE TITLE
follow-ups & to-dos

### ISSUE THREAD

**Issue by obfusk** [CatimaLoyalty/Android#1575]
# follow-ups

- [ ] locale issues https://github.com/CatimaLoyalty/Android/issues/1322#issuecomment-1595696896
- [ ] unused barcode types (9569347983396079d62e196fd2a62ad25d0b5b68) https://github.com/CatimaLoyalty/Android/pull/1386 
- [ ] visual distinction between values and descriptions https://github.com/CatimaLoyalty/Android/pull/1402
- [ ] long vs Long https://github.com/CatimaLoyalty/Android/pull/1434
- [ ] cleanup test https://github.com/CatimaLoyalty/Android/pull/1452
- [ ] contributor that didn't translate https://github.com/CatimaLoyalty/Android/pull/1480
- [ ] automated detection of new languages https://github.com/CatimaLoyalty/Android/pull/1499
- [ ] icon & wording https://github.com/CatimaLoyalty/Android/pull/1512
- [ ] more testing before release https://github.com/CatimaLoyalty/Android/pull/1517
- [ ] `android:label` https://github.com/CatimaLoyalty/Android/pull/1571#issuecomment-1758589331

# to-dos

- [ ] sie/ihr(e) vs du/dein(e) in German
- [ ] automate stocard csv updates w/ apkeep
- [ ] website: contribute with exports
- [ ] binary eye / binarizer
- [ ] move code to kotlin

**Comment by docjyJ** [comment]
Update?

Several Issues are closed and PR are merged.

**Comment by obfusk** [comment]
This is mostly my personal to-do list of open issues I want to look at when I have the time or small things that aren't sufficiently important to have their own issue. And yes, some issues are closed and PRs merged -- but some of those may still have some small detail I want to double-check or follow up on before striking it off *this* list as well.

I *should* indeed update this list and also add some *new* issues and PRs when I have the time; I haven't forgotten about it, and appreciate the reminder.

As you know, Catima is an unpaid hobby project, so I tend to focus on spending my limited time helping Sylvia fix bugs and reviewing PRs :)

**Comment by docjyJ** [comment]
I understand, thank you for this work! :)

**Comment by TheLastProject** [comment]
Nothing personal (as you surely know), but this to-do list being open probably causes more confusion than anything else right now.

A lot of this still needs to be done, so I would request anyone wanting to help with this to show up in the original issues. But yeah.
